version: "3.9"

services:
  notepad-api:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: notepad_server
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb
    networks:
      - notepad-application

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      SECRET: ${SECRET}
    volumes:
      - mongodb-data:/data/db
    networks:
      - notepad-application

  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123456
    volumes:
      - mongodb-data
    networks:
      - notepad-application

  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: notepad_react_frontend
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - notepad-api
    networks:
      - notepad-application

networks:
  notepad-application:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
